# for deciding whether to accept generated test case
import json
import re
import os
from ..config import logger
from ..basic_class.llm_message import MessageThread , FunctionCall
from ..models import model

SYSTEM_PROMPT_REQUIREMENT = '''You are an expert Software Quality Assurance Lead. Your sole responsibility is to audit a "Test Specification Document" generated by a Requirement Analyst.
The goal is to ensure the specification is **Factual**, **Honest**, and **Testable** so that a Test engineer can generate bug-detecting tests.
'''

# REVIEW_REQIREMENT_PROMPT = '''** OBJECTIVE: **
# Ensure the Generated Requirement is:
# 1.  **Factual**: Strictly derived from the Javadoc (for explicit requirements).
# 2.  **Honest**: Clearly distinguishes between explicit rules and inferences.
# 3.  **Internal Consistency**: No contradictions in specification.
# 4.  **Complete**: Covers all logic rules and boundary conditions from Javadoc and method signature.
# 5.  Suspicious Logic and Inference are reasonable.

# **SECTION EXPLAINATION:**
# ## 1. Method Intent: A concise , high-level summary of what the method SHOULD do.
# ## 2. Input/Output Specification:
#    - **Parameters**: Explanation of parameters (semantic meaning and constraints).
#    - *Return Value*: Expected return values for different scenarios (meaning and possible values).
# ## 3. Logic Rules and Branches(Not code path): Describe the core functional paths defined in the Javadoc and Derive all certain logic rules and branches ONLY from:
#    - the Javadoc
#    - the method name and parameters
#    - the explicit domain semantics
#    Do NOT infer new business rules from the implementation.
# ## 4. Boundary Analysis: What should happen on null inputs, empty inputs, invalid inputs, or extreme values?
# ## 5. Suspicious Logic and Inference(Crucial): Use this section to guide the Test engineer on what to test
#    - List undocumented behaviors that are NOT clearly defined in Javadoc as `[Undocumented]`.
#    - If you find the code implementation contradicts the Javadoc or undocumented guards, explicitly point it out here as `[Contradiction]`.
#    - For scenarios marked as "Not Specified" in previous sections, provide your best inference based on code implementation `[Inferred]`.

# **For Sections 1, 2, 3 and 4(Intent, I/O, Logic Rules, Boundary analysis)**:
#     - You must **ONLY** use information that is **EXPLICITLY stated** in the Javadoc or **STRICTLY implied** by the method signature.
#     - **DO NOT GUESS.** Do not infer behavior based on "standard Java conventions" or the actual code implementation in these sections.
#     - If the Javadoc does not specify behavior for a scenario, you can explicitly write: "Not Specified in Javadoc" but not "Should throw Exception".

# **For Section 5 (Suspicious Logic & Inferences)**:
#     - This is the ONLY section where you are allowed to look at the Source Code and infer.

# ** CONSTRAINTS **
# 1.  **READ-ONLY ARTIFACTS**: The Javadoc and Code are **IMMUTABLE LEGACY**. Never suggest update/fix the Javadoc or Code.
# 2.  **SILENCE IS GOLD**: If the specification is accurate to the best of its ability (even if the Javadoc itself is bad), you MUST **APPROVE** it. Do not nitpick on style.
# 3.  **HANDLING JAVADOC GAPS**: If Javadoc is missing info (e.g., null handling), the Analyst MUST document this in **Section 5 (Inference)**. Do NOT reject the spec asking to update Javadoc.

# ** Important: If the Javadoc contradicts the Code, TRUST THE JAVADOC.

# ** OUTPUT FORMAT **:
# {
#     "result": Yes or No,
#     "issues": {
#         {   
#             "issue_section": ... ,
#             "error_type": ... ,
#             "correct instruction": ...
#         },
#         {
#             "issue_section": ... ,
#             "error_type": ... ,
#             "correct instruction": ...
#         }
#     }
# }
# '''

REVIEW_REQIREMENT_PROMPT = '''**SECTION EXPLAINATION:**
## 1. Method Intent: A concise , high-level summary of what the method SHOULD do.
## 2. Input/Output Specification:
   - **Parameters**: Details the inputs required by the code, including input types, formats, and any constraints.
   - *Return Value*: Expected return values including output types, formats, and any constraints.
## 3. Logic Rules and Branches(Not code path): Describe the core functional paths defined in the Javadoc and Derive all certain logic rules and branches ONLY from:
   - the Javadoc
   - the method name and parameters
   - the explicit domain semantics
   Do NOT infer new business rules from the implementation.
## 4. Boundary Analysis: What should happen on null inputs, empty inputs, invalid inputs, or extreme values ?

** CONSTRAINTS **
1.  **READ-ONLY ARTIFACTS**: Never suggest update/fix the Javadoc or signature.
2.  **SILENCE IS GOLD**: If the requirements is accurate to the best of its ability, you MUST **APPROVE** it. Do not nitpick on style.
3.  **HANDLING JAVADOC GAPS**: If Javadoc is missing info , Do NOT reject the spec asking to update Javadoc.

** OUTPUT FORMAT **:
{
    "result": Yes or No,
    "issues": [
        {   
            "issue_section": ... ,
            "error_analysis": ... , 
        },
        {
            "issue_section": ... ,
            "error_analysis": ... ,
        }
    ]
}

Focus your analysis on the following categories:
1. Implementation Leakage: The requirement mention implementation details or rules that are NOT found in the Javadoc.
2. Logical Contradictions & Misinterpretations: Logical errors or internal inconsistency in the requirements.
3. Missing Coverage: Information mentioned in the Javadoc that are missing from the requirements.
'''


# METHOD_INFO = '''** METHOD CONTEXT **
# - Target Method Signature: {method_signature}
# - Javadoc: {javadoc}
# - Source code (UNKNOW to contain bugs): {source_code}

# ** Requirement Specification **
# {requirement_content}
# '''

METHOD_INFO = '''** Target Method **
- Target Method Signature: {method_signature}
- Javadoc: {javadoc}

** Test Requirement **
{requirement_content}
'''

REQUIREMENT_DIR = os.path.join(os.path.dirname(__file__) , '..' , '..' , 'results' , 'detailed_res_info')

class ReviewAgent:
    def __init__(self , role):
        self.role = role
        self.history = []
        self.handle = []
        
        self.all_projects  = None
        self.class_map = None
        self.method_map = None
        self.target_method = None

        self.now_thread = None
    
    def set_up(self , all_projects , class_map , method_map):
        self.all_projects = all_projects
        self.class_map = class_map
        self.method_map = method_map

    def construct_init_thread(self):
        thread = MessageThread()
        if self.role == 'requirement': 
            thread.add_system(SYSTEM_PROMPT_REQUIREMENT)

        return thread

    def analyse_review(self , response):
        pattern = re.compile(r"```json\s*([\s\S]*?)\s*```", re.IGNORECASE)
        results = []

        for m in pattern.finditer(response):
            raw = m.group(1)
            results.append(json.loads(raw))

        return results

    def review_requirement(self , project_name , target_method , max_retrey = 3):
        self.target_method = target_method
        self.role = "requirement"
        group = project_name.split('_')[0]
        file_path = os.path.join(REQUIREMENT_DIR , group , project_name , "requirement_document.txt")
        
        try:
            for try_num in range(max_retrey):
                with open(file_path , 'r' , encoding='utf-8') as f:
                    requirement_content = f.read()
                    f.close()
                
                for index , line in enumerate(requirement_content.split('\n')):
                    if "Suspicious Logic" in line:
                        requirement_content = '\n'.join(requirement_content.split('\n')[:index])
                        break
                
                thread = self.construct_init_thread()
                self.now_thread = thread
                user_prompt = ""
                prefix_prompt = '''Here is the information of Target Method:\n'''
                user_prompt += prefix_prompt + METHOD_INFO.format(method_signature=self.target_method.signature , javadoc=self.target_method.javadoc , source_code=self.target_method.content ,requirement_content=requirement_content)
                thread.add_user(user_prompt)
                thread.add_user(REVIEW_REQIREMENT_PROMPT)

                logger.info(f"Reviewer Agent Prompt:\n{thread.to_msg()}")
                response , *_ = model.REVIEW_MODEL.call(thread.to_msg())
                logger.info(f"Reviewer Agent Response:\n{response}")

                review_results = self.analyse_review(response)[0]

                if review_results['result'].strip() == "No" and len(review_results['issues']) == 0:
                    continue
                  
                return review_results
            
            return None
        except Exception as e:
            print("Exception:" , e)